"""
Django settings for ErpProject project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import logging, inspect

from django.conf import settings


CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hlql0wo@exguedc7l9i70whjljnrezz8r66@2o4v_*@)u^!js9'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_extensions',

    'rest_framework_datatables',
    'django_elasticsearch_dsl',
    'django_celery_results',

    'ErpBackOffice.apps.ErpbackofficeConfig',
    'ModuleComptabilite',
    'ModuleVente',
    'ModuleAchat',
    'ModuleInventaire',
    'ModuleRessourcesHumaines',
    'ModuleArchivage',
    'ModuleConversation',
    'ModuleConfiguration',
    'ModuleApplication',
    'ModuleBudget',
    'ModuleCalendrier'
]

ELASTICSEARCH_DSL = {
    'default': {
        # Normal Config
        # 'hosts': 'localhost:9200'

        # Docker config
        'hosts': 'elasticsearch_arpce:9200'

    },
}


CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
#CELERY_BROKER_URL = 'redis://10.1.1.18:6379'
#CELERY_RESULT_BACKEND = 'redis://10.1.1.18:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ErpProject.urls'

TEMPLATES = [
    {
        #'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, "templates"), 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ErpProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    } 
}'''

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'DB_ERP_NSDX_PREPROD',
        'USER': 'dev',
        'PASSWORD': 'Password01',

        # Arpce Config
        'HOST': '10.17.1.130',

        # Local Config
        # 'HOST': 'localhost',

        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# DATABASES = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',
#         'NAME': 'BDD_ERP_ARPCE_V1',
#         'USER': 'dev',
#         'PASSWORD': 'Password01',
#         'HOST': '93.115.18.119',
#         'PORT': '',

#         'OPTIONS': {
#             'driver': 'ODBC Driver 13 for SQL Server',
#         },
#     },
# }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_datatables.filters.DatatablesFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
    'PAGE_SIZE': 50,
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# STATIC_ROOTCUSTUMER = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/ErpProject/image/upload/'
MEDIA_ROOT = os.path.join(BASE_DIR, "/static/image/upload")
base_dir = BASE_DIR
base_dir = base_dir.replace("\\", "/")

MEDIA_ROOT = BASE_DIR + '/static/ErpProject/image/upload'
DOWNLOAD_DIR = base_dir + '/static/ErpProject/download'
CSS_DIR = BASE_DIR + '/static/ErpProject/css'

"""
STATIC_ROOT = 'static'
STATIC_URL = '/static/'
MEDIA_ROOT = 'upload'
MEDIA_URL = '/upload/'
"""
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'noreply.nsandax@gmail.com'
EMAIL_HOST_PASSWORD = 'Ns@ndax01'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

#CONFIGURATION DES LOGS

dir = os.getcwd()
dir_log = dir+"/logs"
if os.path.exists(dir_log)==False:
    os.makedirs(dir_log)
    with open(dir_log+"/Log.log", 'a') as f:
        pass

logging.basicConfig(filename =dir_log+"/Log.log", format = '%(levelname)s :: %(module)s :: %(asctime)s :: %(message)s \n###############################################################', level=logging.INFO)

DATE_FORMAT = '%d/%m/%Y -- %I:%M'
DATE = '%d/%m/%Y'
HEURE = '%I:%M'


##
# 2. Configuration of CubesViewer Server
##

# Base Cubes Server URL.
# Your Cubes Server needs to be running and listening on this URL, and it needs
# to be accessible to clients of the application.
CUBESVIEWER_CUBES_URL = "http://10.10.14.100:5000"

# CubesViewer Store backend URL. It should point to this application.
# Note that this must match the URL that you use to access the application,
# otherwise you may hit security issues. If you access your server
# via http://localhost:8000, use the same here. Note that 127.0.0.1 and
# 'localhost' are different strings for this purpose. (If you wish to accept
# requests from different URLs, you may need to add CORS support).
CUBESVIEWER_BACKEND_URL = "http://10.10.14.100:8000/controle/explore"

# Optional user and password tuple to access the backend, or False
# (only applies when CubesViewer Cubes proxy is used)
#CUBESVIEWER_CUBES_PROXY_USER = ('user', 'password')
CUBESVIEWER_CUBES_PROXY_USER = None

# CubesViewer Proxy ACL
# (only applies when CubesViewer Cubes proxy is used)
# ie. CUBESVIEWER_PROXY_ACL = [ { "cube": "my_cube", "group": "my_group" } ]
CUBESVIEWER_PROXY_ACL = [ ]


INSTALLED_APPS.append('ModulePayroll')
INSTALLED_APPS.append('ModuleControle')

INSTALLED_APPS.append('ModuleContrat')
INSTALLED_APPS.append('ModuleStock')