# Generated by Django 2.1 on 2021-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_reglesalariale',
            name='reference',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
