# Generated by Django 2.1.7 on 2021-09-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0002_model_reglesalariale_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_employe',
            name='statutrh',
        ),
    ]
