# Generated by Django 2.1 on 2021-09-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0002_model_reglesalariale_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_LieuTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='model_employe',
            name='date_entree',
        ),
        migrations.RemoveField(
            model_name='model_employe',
            name='est_permanent',
        ),
        migrations.RemoveField(
            model_name='model_employe',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='model_personne',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='model_personne',
            name='civilite',
        ),
        migrations.RemoveField(
            model_name='model_personne',
            name='date_de_naissance',
        ),
        migrations.RemoveField(
            model_name='model_personne',
            name='langue',
        ),
        migrations.RemoveField(
            model_name='model_personne',
            name='lieu_de_naissance',
        ),
        migrations.RemoveField(
            model_name='model_personne',
            name='postnom',
        ),
        migrations.RemoveField(
            model_name='model_personne',
            name='type',
        ),
        migrations.RemoveField(
            model_name='model_poste',
            name='classification_pro',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='adresse_banque',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='classificaion',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='code_swift',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='compte_bancaire',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='dependant',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='designation_banque',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='education',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='est_enconge',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='lieu_exercice',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='lieu_travail',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='permis',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='responsable_id',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='seconde_nationalite',
        ),
        migrations.RemoveField(
            model_name='model_profilrh',
            name='situation_famille',
        ),
        migrations.AddField(
            model_name='model_employe',
            name='classification_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes', to='ErpBackOffice.Model_ClassificationProfessionelle'),
        ),
        migrations.AddField(
            model_name='model_profilrh',
            name='est_permanent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='model_lieutravail',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_lieu_travail', to='ErpBackOffice.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_lieutravail',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape'),
        ),
        migrations.AddField(
            model_name='model_employe',
            name='lieu_travail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_LieuTravail'),
        ),
    ]
