# Generated by Django 2.1 on 2021-09-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0003_auto_20210912_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_employe',
            name='type_structure',
        ),
    ]
