# Generated by Django 2.1.7 on 2021-09-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0003_remove_model_employe_statutrh'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employe',
            name='statutrh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_statut_employes', to='ErpBackOffice.Model_StatusRH'),
        ),
    ]
