# Generated by Django 2.1 on 2021-09-15 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0004_remove_model_employe_type_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_employe',
            name='modele_bulletin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_modele_bulletin', to='ErpBackOffice.Model_BulletinModele'),
        ),
    ]
