# Generated by Django 2.1.7 on 2021-09-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0005_remove_model_employe_statutrh'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employe',
            name='statutrh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
