# Generated by Django 2.1 on 2021-09-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0005_auto_20210915_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_profilrh',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
