# Generated by Django 2.1 on 2021-09-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0006_model_profilrh_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_paiement',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='ErpBackOffice.Model_Transaction'),
        ),
        migrations.AlterField(
            model_name='model_wkf_historique',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_utilisateurs', to='ErpBackOffice.Model_Employe'),
        ),
        migrations.AlterField(
            model_name='model_wkf_historique',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_etapes', to='ErpBackOffice.Model_Wkf_Etape'),
        ),
    ]
