# Generated by Django 2.1 on 2021-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0007_auto_20210917_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_classificationprofessionelle',
            name='numero_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
