# Generated by Django 2.1.7 on 2021-09-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0007_auto_20210918_1237'),
        ('ErpBackOffice', '0008_auto_20210918_1755'),
    ]

    operations = [
    ]
