# Generated by Django 2.1.7 on 2021-09-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0009_merge_20210919_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_MobiliteEmploye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type_mobilite', models.IntegerField(blank=True, choices=[(1, 'Recrutement'), (2, 'Promotion'), (3, 'Mutation'), (4, 'Détachement'), (5, 'Démission'), (6, 'Départ Définitif'), (7, 'Départ provisoire')], default=1, max_length=100, null=True)),
                ('date_mobilite', models.DateTimeField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_mobilite_employe_gny', to='ErpBackOffice.Model_Personne')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_rh_mob_fk', to='ErpBackOffice.Model_CategorieRH')),
                ('classification_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_pro_mobilite', to='ErpBackOffice.Model_ClassificationProfessionelle')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_of_mobilite_nhg', to='ErpBackOffice.Model_Employe')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Poste')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape')),
            ],
        ),
        migrations.AlterField(
            model_name='model_mobilite',
            name='type_mobilite',
            field=models.CharField(blank=True, choices=[(1, 'Recrutement'), (2, 'Promotion'), (3, 'Mutation'), (4, 'Détachement'), (5, 'Démission'), (6, 'Départ Définitif'), (7, 'Départ provisoire')], default='Promotion', max_length=100, null=True),
        ),
    ]
