# Generated by Django 2.1.7 on 2021-09-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0010_auto_20210919_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_activite',
            name='etat',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_activite',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statut_fgtk_hgk_mission', to='ErpBackOffice.Model_Wkf_Etape'),
        ),
        migrations.AddField(
            model_name='model_groupeanalytique',
            name='etat',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_groupeanalytique',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statut_pok_hgk_mission', to='ErpBackOffice.Model_Wkf_Etape'),
        ),
        migrations.AlterField(
            model_name='model_mobiliteemploye',
            name='type_mobilite',
            field=models.IntegerField(choices=[(1, 'Recrutement'), (2, 'Promotion'), (3, 'Mutation'), (4, 'Détachement'), (5, 'Démission'), (6, 'Départ Définitif'), (7, 'Départ provisoire')], default=1),
        ),
    ]
