# Generated by Django 2.1.7 on 2021-09-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0011_auto_20210926_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_transactionbudgetaire',
            old_name='statut',
            new_name='status',
        ),
    ]
