# Generated by Django 2.1.7 on 2021-10-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ErpBackOffice', '0013_auto_20210926_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Wkf_Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('est_delegation', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('carbon_copy', models.ManyToManyField(related_name='copie_information', to='ErpBackOffice.Model_Employe')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('employes', models.ManyToManyField(related_name='destinataires', to='ErpBackOffice.Model_Employe')),
            ],
        ),
        migrations.RenameField(
            model_name='model_wkf_etape',
            old_name='est_decisive',
            new_name='est_echec',
        ),
        migrations.RenameField(
            model_name='model_wkf_etape',
            old_name='est_finale',
            new_name='est_succes',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='bon',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='bon_reception',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='bon_transfert',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='demande_achat',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='etat_facturation',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='model_wkf_historique',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='model_wkf_transition',
            name='identifiant_cle',
        ),
        migrations.RemoveField(
            model_name='model_wkf_transition',
            name='num_ordre',
        ),
        migrations.AddField(
            model_name='model_wkf_historique',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='model_wkf_transition',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='model_wkf_transition',
            name='est_configurable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_wkf_transition',
            name='filtre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='model_wkf_transition',
            name='operateur',
            field=models.IntegerField(choices=[(1, 'AND'), (2, 'OR')], default=1),
        ),
        migrations.AddField(
            model_name='model_wkf_stakeholder',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_stakeholder', to='ErpBackOffice.Model_Wkf_Transition'),
        ),
    ]
