# Generated by Django 2.1 on 2021-09-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0013_auto_20210926_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_operationnalisation_module',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape'),
        ),
    ]
