# Generated by Django 2.1 on 2021-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0014_model_operationnalisation_module_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='correspondant',
            field=models.ManyToManyField(blank=True, null=True, related_name='correspondants_lignes_bgt', to='ErpBackOffice.Model_Personne'),
        ),
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='type',
            field=models.IntegerField(choices=[(1, 'Exploitation'), (2, 'Projet')], default=1),
        ),
    ]
