# Generated by Django 2.1.7 on 2021-10-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0014_auto_20211003_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_wkf_transition',
            name='est_filtrable',
            field=models.BooleanField(default=False),
        ),
    ]
