# Generated by Django 2.1 on 2021-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0014_model_operationnalisation_module_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='is_bloqued',
            field=models.BooleanField(default=False),
        ),
    ]
