# Generated by Django 2.1.7 on 2021-10-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0015_model_wkf_transition_est_filtrable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_wkf_transition',
            name='content_type',
        ),
    ]
