# Generated by Django 2.1 on 2021-09-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0015_auto_20210928_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='correspondant',
            field=models.ManyToManyField(related_name='correspondants_lignes_bgt', to='ErpBackOffice.Model_Personne'),
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Exploitation'), (2, 'Projet')], default=1, null=True),
        ),
    ]
