# Generated by Django 2.1 on 2021-09-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0016_auto_20210928_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets_lignes_kg', to='ErpBackOffice.Model_Budget'),
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='correspondant',
            field=models.ManyToManyField(blank=True, null=True, related_name='correspondants_lignes_bgt', to='ErpBackOffice.Model_Personne'),
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='entite',
            field=models.CharField(blank=True, default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='nature_charge',
            field=models.IntegerField(blank=True, choices=[(0, 'Variable'), (1, 'Fixe'), (2, 'Budget'), (3, 'Nature')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets_lignes', to='ErpBackOffice.Model_Employe'),
        ),
    ]
