# Generated by Django 2.1.7 on 2021-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0016_remove_model_wkf_transition_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_wkf_transition',
            name='est_delegable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='model_wkf_transition',
            name='operateur',
            field=models.IntegerField(choices=[(1, 'OR'), (2, 'AND')], default=1),
        ),
    ]
