# Generated by Django 2.1.7 on 2021-10-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0017_auto_20211004_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_wkf_stakeholder',
            old_name='carbon_copy',
            new_name='carbon_copies',
        ),
    ]
