# Generated by Django 2.1 on 2021-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0017_auto_20210928_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='correspondant',
            field=models.ManyToManyField(related_name='correspondants_lignes_bgt', to='ErpBackOffice.Model_Personne'),
        ),
    ]
