# Generated by Django 2.1.7 on 2021-10-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0018_auto_20211004_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_wkf_stakeholder',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_wkf_stakeholder', to='ErpBackOffice.Model_Personne'),
        ),
    ]
