# Generated by Django 2.1.7 on 2021-10-04 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0019_model_wkf_stakeholder_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_wkf_stakeholder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_wkf_stakeholder',
            name='module_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_wkf_stakeholder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='model_wkf_stakeholder',
            name='url_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
