# Generated by Django 2.1.7 on 2021-10-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0020_auto_20211004_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_notification',
            name='avis_appel_offre',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='bon',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='bon_reception',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='bon_transfert',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='conge',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='dossier_social',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='model_notification',
            name='requete',
        ),
    ]
