# Generated by Django 2.1.7 on 2021-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0021_auto_20211004_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_wkf_transition',
            name='est_generate_doc',
            field=models.BooleanField(default=False),
        ),
    ]
