# Generated by Django 2.1.7 on 2021-10-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0022_model_wkf_transition_est_generate_doc'),
        ('ErpBackOffice', '0015_model_lignebudgetaire_is_bloqued'),
        ('ErpBackOffice', '0018_auto_20210928_1044'),
    ]

    operations = [
    ]
