# Generated by Django 2.1.7 on 2021-10-06 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ErpBackOffice', '0023_merge_20211005_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('titulaire', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('montant', models.FloatField()),
                ('financement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_contrat', models.DateTimeField()),
                ('document_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_contrat_soh', to='ErpBackOffice.Model_Personne')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devise_fk_ooi', to='ErpBackOffice.Model_Devise')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Demande_cotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('montant', models.FloatField()),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_demande_cotation_gvb', to='ErpBackOffice.Model_Personne')),
                ('demande_achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_achat_fk_plg', to='ErpBackOffice.Model_Demande_achat')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devise_fk_dvi', to='ErpBackOffice.Model_Devise')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_fk_gtn', to='ErpBackOffice.Model_Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Lettre_commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('montant', models.FloatField()),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_lettre_commande_kdn', to='ErpBackOffice.Model_Personne')),
                ('demande_achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_achat_fk_fcl', to='ErpBackOffice.Model_Demande_achat')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devise_fk_nrp', to='ErpBackOffice.Model_Devise')),
            ],
        ),
        migrations.CreateModel(
            name='Model_TypeMarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_typemarche_avo', to='ErpBackOffice.Model_Personne')),
            ],
        ),
        migrations.AddField(
            model_name='model_lettre_commande',
            name='type_marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_marche_fk_bnl', to='ErpBackOffice.Model_TypeMarche'),
        ),
        migrations.AddField(
            model_name='model_demande_cotation',
            name='type_marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_marche_fk_wag', to='ErpBackOffice.Model_TypeMarche'),
        ),
    ]
