# Generated by Django 2.1.7 on 2021-10-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0024_auto_20211006_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='is_waiting_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='user_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Employe'),
        ),
    ]
