# Generated by Django 2.1.7 on 2021-10-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0026_auto_20211006_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_avis_appel_offre',
            name='type_appel_offre',
            field=models.IntegerField(choices=[(1, 'Restreint'), (2, 'Ouvert'), (3, 'Gré à Gré')], default=1),
        ),
    ]
