# Generated by Django 2.1.7 on 2021-10-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0027_auto_20211006_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_avis_appel_offre',
            name='type_marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_marche_avis', to='ErpBackOffice.Model_TypeMarche'),
        ),
    ]
