# Generated by Django 2.1.7 on 2021-10-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0028_model_avis_appel_offre_type_marche'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_contrat',
            name='appel_offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appel_offre_dk', to='ErpBackOffice.Model_Devise'),
        ),
        migrations.AddField(
            model_name='model_contrat',
            name='demande_cotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_cotation_fk', to='ErpBackOffice.Model_Demande_cotation'),
        ),
        migrations.AlterField(
            model_name='model_avis_appel_offre',
            name='date_depot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model_avis_appel_offre',
            name='date_signature',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
