# Generated by Django 2.1.7 on 2021-10-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0029_auto_20211006_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_contrat',
            name='appel_offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appel_offre_dk', to='ErpBackOffice.Model_Avis_appel_offre'),
        ),
    ]
