# Generated by Django 2.1.7 on 2021-10-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0030_auto_20211006_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_transactionbudgetaire',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='model_transactionbudgetaire',
            name='poste_budgetaire',
        ),
        migrations.RemoveField(
            model_name='model_transactionbudgetaire',
            name='reel',
        ),
        migrations.AddField(
            model_name='model_transactionbudgetaire',
            name='ecriture_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecriture_of_transaction', to='ErpBackOffice.Model_EcritureComptable'),
        ),
    ]
