# Generated by Django 2.1.7 on 2021-10-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0031_auto_20211007_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_transactionbudgetaire',
            name='ecriture_comptable',
        ),
        migrations.AddField(
            model_name='model_transactionbudgetaire',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_of_transaction', to='ErpBackOffice.Model_Compte'),
        ),
    ]
