# Generated by Django 2.1.7 on 2021-10-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0032_auto_20211007_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_ligne_facture',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Compte'),
        ),
    ]
