# Generated by Django 2.1.7 on 2021-10-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0033_model_ligne_facture_compte_comptable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_avis_appel_offre',
            old_name='objet_appel',
            new_name='intitule',
        ),
        migrations.RenameField(
            model_name='model_demande_cotation',
            old_name='numero',
            new_name='financement',
        ),
        migrations.RenameField(
            model_name='model_lettre_commande',
            old_name='numero',
            new_name='financement',
        ),
        migrations.AddField(
            model_name='model_avis_appel_offre',
            name='nombre_lots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model_demande_cotation',
            name='intitule',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_demande_cotation',
            name='nombre_lots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model_demande_cotation',
            name='numero_reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_lettre_commande',
            name='intitule',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_lettre_commande',
            name='nombre_lots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model_lettre_commande',
            name='numero_reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
