# Generated by Django 2.1.7 on 2021-10-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0034_auto_20211008_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_typemarche',
            name='url_interne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
