# Generated by Django 2.1.7 on 2021-10-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0035_model_typemarche_url_interne'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_avis_appel_offre',
            name='devise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Devise'),
        ),
        migrations.AddField(
            model_name='model_avis_appel_offre',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
