# Generated by Django 2.1.7 on 2021-10-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0036_auto_20211008_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_contrat',
            name='date_echeance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_contrat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_contrat_gtn', to='ErpBackOffice.Model_Fournisseur'),
        ),
        migrations.AlterField(
            model_name='model_contrat',
            name='date_contrat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
