# Generated by Django 2.1.7 on 2021-10-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0037_auto_20211008_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_contrat',
            old_name='date_contrat',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='model_contrat',
            old_name='date_echeance',
            new_name='date_fin',
        ),
        migrations.RemoveField(
            model_name='model_contrat',
            name='financement',
        ),
        migrations.RemoveField(
            model_name='model_contrat',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='model_contrat',
            name='titulaire',
        ),
        migrations.AddField(
            model_name='model_contrat',
            name='type_marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_marche_of_contrat', to='ErpBackOffice.Model_TypeMarche'),
        ),
    ]
