# Generated by Django 2.1.7 on 2021-10-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0038_auto_20211008_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_contrat',
            name='numero_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
