# Generated by Django 2.1.7 on 2021-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0039_model_contrat_numero_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_contrat',
            name='document_id',
            field=models.IntegerField(default=0),
        ),
    ]
