# Generated by Django 2.1.7 on 2021-10-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0040_auto_20211008_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_avis_appel_offre',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_fk_ao', to='ErpBackOffice.Model_Fournisseur'),
        ),
        migrations.AddField(
            model_name='model_contrat',
            name='modalite',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='model_lettre_commande',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_fk_lc', to='ErpBackOffice.Model_Fournisseur'),
        ),
    ]
