# Generated by Django 2.1.7 on 2021-10-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0041_auto_20211008_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_OperationContrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.IntegerField(choices=[(1, 'Facture'), (2, 'Avenant')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Montant fixe'), (2, 'Pourcentage')], default=1)),
                ('montant', models.FloatField(default=0)),
                ('reference_document', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_dde_model_contrat_soh', to='ErpBackOffice.Model_Personne')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ErpBackOffice.Model_Contrat')),
                ('devise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devise_ddfk_ooi', to='ErpBackOffice.Model_Devise')),
            ],
        ),
        migrations.AlterField(
            model_name='model_operationtresorerie',
            name='type_operation',
            field=models.CharField(blank=True, choices=[(1, 'Montant fixe'), (2, 'Pourcentage')], default='', max_length=100, null=True),
        ),
    ]
