# Generated by Django 2.1.7 on 2021-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0042_auto_20211008_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_operationcontrat',
            old_name='montant',
            new_name='valeur',
        ),
        migrations.AddField(
            model_name='model_operationcontrat',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
