# Generated by Django 2.1.7 on 2021-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0043_auto_20211008_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_operationcontrat',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Facture'), (2, 'Avenant (+)'), (3, 'Avenant (-)')], default=1),
        ),
        migrations.AlterField(
            model_name='model_operationcontrat',
            name='type',
            field=models.IntegerField(choices=[(1, 'Facture'), (2, 'Avenant (+)'), (3, 'Avenant (-)')], default=1),
        ),
    ]
