# Generated by Django 2.1.7 on 2021-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0044_auto_20211008_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_operationcontrat',
            name='type',
            field=models.IntegerField(choices=[(1, 'Montant fixe'), (2, 'Pourcentage')], default=1),
        ),
    ]
