# Generated by Django 2.1 on 2021-10-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0045_auto_20211008_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Compte'),
        ),
        migrations.AlterField(
            model_name='model_avis_appel_offre',
            name='type_appel_offre',
            field=models.IntegerField(choices=[(0, 'Restreint'), (1, 'National'), (2, 'International'), (3, 'Gré à Gré')], default=1),
        ),
        migrations.AlterField(
            model_name='model_operationcontrat',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrat_of_op', to='ErpBackOffice.Model_Contrat'),
        ),
    ]
