# Generated by Django 2.1 on 2021-10-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0046_auto_20211030_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_actionutilisateur',
            name='nom_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model_actionutilisateur',
            name='ref_action',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
