# Generated by Django 2.1 on 2021-10-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0048_auto_20211030_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='compte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Compte'),
        ),
    ]
