# Generated by Django 2.1 on 2021-10-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0049_auto_20211030_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_lignebudgetaire',
            name='poste_budgetaire',
        ),
    ]
