# Generated by Django 2.1.14 on 2021-12-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ErpBackOffice', '0050_remove_model_lignebudgetaire_poste_budgetaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_module',
            name='nom_application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_moduleovermodel',
            name='model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
