# Generated by Django 2.1 on 2022-02-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0051_auto_20211202_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='is_reportable',
            field=models.BooleanField(default=False),
        ),
    ]
