# Generated by Django 2.1 on 2022-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0052_model_lignebudgetaire_is_reportable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='is_reportable',
            field=models.BooleanField(default=True),
        ),
    ]
