# Generated by Django 2.1 on 2022-02-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0053_auto_20220225_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_client',
            name='bp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='fiscale',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='mode_reglement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_condition_reglement', to='ErpBackOffice.Model_ConditionReglement'),
        ),
        migrations.AddField(
            model_name='model_client',
            name='nui',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='numero_compte_b',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='personne_contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='raison_sociale',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
