# Generated by Django 2.1 on 2022-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0054_auto_20220228_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_client',
            name='date_de_naissance',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='langue',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='model_client',
            name='lieu_de_naissance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
