# Generated by Django 2.1 on 2022-03-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0055_auto_20220302_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_client',
            name='autre_info',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
