# Generated by Django 2.1.14 on 2022-03-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0056_model_client_autre_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Type_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default=100, max_length=100, verbose_name='Designation')),
                ('designation_courte', models.CharField(blank=True, default=100, max_length=100, null=True, verbose_name='Designation courte')),
                ('description', models.CharField(blank=True, default=510, max_length=510, null=True, verbose_name='Description')),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_type_service', to='ErpBackOffice.Model_Personne')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape')),
            ],
            options={
                'verbose_name': 'Type de service',
                'verbose_name_plural': 'Types de service',
            },
        ),
        migrations.AddField(
            model_name='model_facture',
            name='est_facture_acompte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_facture',
            name='objet_facture',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='model_facture',
            name='type_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='ErpBackOffice.Model_Type_service'),
        ),
    ]
