# Generated by Django 2.1 on 2022-03-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0057_auto_20220303_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_bon_reception',
            name='duree',
            field=models.IntegerField(blank=True, choices=[(1, '6 Mois'), (2, '12 Mois')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='model_bon_reception',
            name='is_actif',
            field=models.BooleanField(default=True),
        ),
    ]
