# Generated by Django 2.1 on 2022-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0058_auto_20220306_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_bon_transfert',
            name='is_return_materiel',
            field=models.BooleanField(default=False),
        ),
    ]
