# Generated by Django 2.1 on 2022-03-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0059_model_bon_transfert_is_return_materiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Bon_retour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon_retour', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_retour', models.DateTimeField(auto_now=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('montant_global', models.FloatField(default=0.0)),
                ('est_realisee', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('reference_document', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_charge_du_bon_retour', to='ErpBackOffice.Model_Employe')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_bon_retour', to='ErpBackOffice.Model_Personne')),
                ('emplacement_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplacement_bon_retour', to='ErpBackOffice.Model_Emplacement')),
                ('emplacement_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_bon_retour', to='ErpBackOffice.Model_Emplacement')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_bon_retour', to='ErpBackOffice.Model_Employe')),
                ('operation_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bon_retour_tranferts', to='ErpBackOffice.Model_OperationStock')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandeur_doing_bon_retour', to='ErpBackOffice.Model_Employe')),
                ('services_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_referent_bon_retour', to='ErpBackOffice.Model_Unite_fonctionnelle')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statut_bon_retour', to='ErpBackOffice.Model_Wkf_Etape')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Ligne_bon_retour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.IntegerField()),
                ('quantite_fournie', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bon_retour_auteur_ligne', to='ErpBackOffice.Model_Personne')),
                ('bon_retour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_of_bon_retour', to='ErpBackOffice.Model_Bon_retour')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape')),
                ('stock_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_bon_retour_take_on_stock_article', to='ErpBackOffice.Model_StockArticle')),
            ],
        ),
    ]
