# Generated by Django 2.1 on 2022-03-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0060_model_bon_retour_model_ligne_bon_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_mouvement_stock',
            name='bon_retour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bon_commande_of_mouvement_stock', to='ErpBackOffice.Model_Bon_retour'),
        ),
    ]
