# Generated by Django 2.1 on 2022-03-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0061_model_mouvement_stock_bon_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_immobilisation',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immobilisations', to='ErpBackOffice.Model_Personne'),
        ),
    ]
