# Generated by Django 2.1 on 2022-03-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0062_auto_20220311_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_immobilisation',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immobilisations', to='ErpBackOffice.Model_Personne'),
        ),
    ]
