# Generated by Django 2.1 on 2022-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0063_auto_20220312_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_immobilisation',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
