# Generated by Django 2.1 on 2022-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0064_auto_20220313_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_traitementimmobilisation',
            name='type_traitement',
            field=models.IntegerField(choices=[(1, 'Cession'), (2, 'Mise au rebut')], default=2),
        ),
    ]
