# Generated by Django 2.1 on 2022-04-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ErpBackOffice', '0064_auto_20220313_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction')),
                ('is_chart', models.BooleanField(default=True)),
                ('model_chart', models.IntegerField(choices=[(0, 'Graphiques recommandés'), (1, 'Barchart'), (2, 'Doughnut Chart'), (3, 'Horizontal Chart')])),
                ('query_string', models.CharField(default='', max_length=1000, verbose_name='Requête SQL')),
                ('select', models.CharField(blank=True, default='*', max_length=1000, null=True, verbose_name='Selection')),
                ('filter', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Filtrage')),
                ('measure_function', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Filtrage')),
                ('measure_attribute', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Filtrage')),
                ('dimension', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Filtrage')),
                ('is_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_query', to='ErpBackOffice.Model_Personne')),
                ('main_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
    ]
