# Generated by Django 2.1 on 2022-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0065_model_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_query',
            name='query_graphic',
            field=models.CharField(default='', max_length=1000, verbose_name='Requête SQL'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='dimension',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='measure_attribute',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Attribut de mesure'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='measure_function',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Fonction de mesure'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre'),
        ),
    ]
