# Generated by Django 2.1 on 2022-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0066_auto_20220406_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_query',
            name='card_attribute',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Attribut de mesure'),
        ),
        migrations.AddField(
            model_name='model_query',
            name='card_function',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Fonction de mesure'),
        ),
        migrations.AddField(
            model_name='model_query',
            name='is_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_query',
            name='query_card',
            field=models.CharField(default='', max_length=1000, verbose_name='Requête SQL'),
        ),
    ]
