# Generated by Django 2.1 on 2022-03-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0067_auto_20220314_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Rebut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.FloatField()),
                ('document', models.CharField(blank=True, max_length=25, null=True)),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_rebut_article', to='ErpBackOffice.Model_Article')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_auteur_rebut_stock', to='ErpBackOffice.Model_Personne')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_emplacement_rebut', to='ErpBackOffice.Model_Emplacement')),
                ('emplacement_rebut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_emplacement_rebut_destination', to='ErpBackOffice.Model_Emplacement')),
                ('serie_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_serie_rebut', to='ErpBackOffice.Model_Asset')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaire_statut_rebut', to='ErpBackOffice.Model_Wkf_Etape')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_unite_rebut', to='ErpBackOffice.Model_Unite')),
            ],
        ),
    ]
