# Generated by Django 2.1 on 2022-03-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0068_model_rebut'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_rebut',
            name='type_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rebut_operation', to='ErpBackOffice.Model_OperationStock'),
        ),
    ]
