# Generated by Django 2.1 on 2022-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0068_auto_20220422_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_query',
            name='model_chart',
            field=models.IntegerField(blank=True, choices=[(0, 'Graphiques recommandés'), (1, 'Barchart'), (2, 'Doughnut Chart'), (3, 'Horizontal Chart')], default=0, null=True),
        ),
    ]
