# Generated by Django 2.1 on 2022-08-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0069_model_rebut_type_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_temp_Nbre_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_end_date', models.DateTimeField(blank=True, null=True)),
                ('payroll_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('element_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reporting_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('class_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('entry_start_date', models.DateTimeField(blank=True, null=True)),
                ('entry_end_date', models.DateTimeField(blank=True, null=True)),
                ('input_value_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('resultat_value', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('employe_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cl_ret', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='model_bulletin',
            name='departemant',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='model_bulletin',
            name='diplome',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='model_bulletin',
            name='fonction',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='model_bulletin',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
