# Generated by Django 2.1 on 2022-08-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0069_auto_20220422_1537'),
        ('ErpBackOffice', '0067_auto_20220314_1119'),
    ]

    operations = [
    ]
