# Generated by Django 2.1 on 2022-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0070_auto_20220825_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_bulletin',
            name='cycle_diplome',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_bulletin',
            name='nombrepart',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='model_rubrique',
            name='est_patronal',
            field=models.BooleanField(default=False),
        ),
    ]
