# Generated by Django 2.1 on 2022-08-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0070_merge_20220826_0654'),
        ('ErpBackOffice', '0071_auto_20220826_0632'),
    ]

    operations = [
    ]
