# Generated by Django 2.1.15 on 2022-09-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0072_merge_20220826_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('etat', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_nature_hgp', to='ErpBackOffice.Model_Personne')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statut_fgtk_hgk_nature', to='ErpBackOffice.Model_Wkf_Etape')),
            ],
        ),
        migrations.AlterField(
            model_name='model_query',
            name='card_attribute',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Card:  Attribut de mesure'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='card_function',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Card: Fonction de mesure'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='measure_attribute',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Graphic:Attribut de mesure'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='measure_function',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Graphic: Fonction de mesure '),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='query_card',
            field=models.CharField(default='', max_length=1000, verbose_name='Requête SQL Card'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='query_graphic',
            field=models.CharField(default='', max_length=1000, verbose_name='Requête SQL Graphic'),
        ),
        migrations.AlterField(
            model_name='model_query',
            name='query_string',
            field=models.CharField(default='', max_length=1000, verbose_name='Requête SQL DataTable'),
        ),
    ]
