# Generated by Django 2.1.15 on 2022-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0073_auto_20220926_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lieutravail',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
