# Generated by Django 2.1.15 on 2022-09-26 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0074_model_lieutravail_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_TypeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='model_client',
            name='typeclient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_type', to='ErpBackOffice.Model_TypeClient'),
        ),
    ]
