# Generated by Django 2.1.15 on 2022-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0075_auto_20220926_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employe',
            name='person_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
