# Generated by Django 2.1.15 on 2022-09-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0076_model_employe_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_asset',
            name='asset_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='model_asset',
            name='attribute_categorie_code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='model_asset',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
