# Generated by Django 2.1.15 on 2022-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0077_auto_20220927_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_asset',
            name='asset_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
