# Generated by Django 2.1.15 on 2022-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0078_model_asset_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Combinaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externe_id', models.IntegerField(blank=True, null=True)),
                ('compte', models.CharField(blank=True, max_length=300, null=True)),
                ('segment_3', models.CharField(blank=True, max_length=300, null=True)),
                ('segment_4', models.CharField(blank=True, max_length=300, null=True)),
                ('segment_5', models.CharField(blank=True, max_length=300, null=True)),
                ('segment_6', models.CharField(blank=True, max_length=300, null=True)),
                ('segment_7', models.CharField(blank=True, max_length=300, null=True)),
                ('segment_8', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='model_ecriturecomptable',
            name='externe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_piececomptable',
            name='est_a_nouveau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_piececomptable',
            name='externe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model_ecriturecomptable',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='model_piececomptable',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='model_piececomptable',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
