# Generated by Django 2.1.15 on 2022-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0079_auto_20221002_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_bon_reception',
            name='po_header_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
