# Generated by Django 2.1.15 on 2022-10-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0080_model_bon_reception_po_header_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_bon_reception',
            name='segment1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
