# Generated by Django 2.1.15 on 2022-10-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0081_model_bon_reception_segment1'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_ligne_reception',
            name='polineID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
