# Generated by Django 2.1.15 on 2022-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0082_model_ligne_reception_polineid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_regorupement_budgetaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.CharField(blank=True, max_length=300, null=True)),
                ('compte', models.CharField(blank=True, max_length=25, null=True)),
                ('detail_compte', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
