# Generated by Django 2.1.15 on 2022-10-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0083_model_regorupement_budgetaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_GroupementCombinaisonB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_regourpe_budgets', to='ErpBackOffice.Model_Personne')),
                ('categoriebudget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ErpBackOffice.Model_Categoriebudget')),
            ],
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='nature_charge',
            field=models.IntegerField(blank=True, choices=[(1, 'Fixe'), (2, 'Budget')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='model_groupementcombinaisonb',
            name='lignebudgetaire',
            field=models.ManyToManyField(blank=True, related_name='lignebudgetaire_related_to_a_group', to='ErpBackOffice.Model_LigneBudgetaire'),
        ),
        migrations.AddField(
            model_name='model_groupementcombinaisonb',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape'),
        ),
    ]
