# Generated by Django 2.1.15 on 2022-10-08 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0084_auto_20221008_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_groupementcombinaisonb',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
