# Generated by Django 2.1.15 on 2022-10-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0085_model_groupementcombinaisonb_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='exericebudgetaires',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ErpBackOffice.Model_Exercicebudgetaire'),
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='nature_charge',
            field=models.IntegerField(blank=True, choices=[(0, 'Fixe'), (1, 'Budget')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='model_lignebudgetaire',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Exploitation'), (2, 'Projet'), (3, 'Activité')], default=1, null=True),
        ),
    ]
