# Generated by Django 2.1.15 on 2022-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0086_auto_20221009_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_lignebudgetaire',
            name='lastyearrepart',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
