# Generated by Django 2.1.15 on 2022-10-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0087_model_lignebudgetaire_lastyearrepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_bon_reception',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bon_reception_contrat', to='ErpBackOffice.Model_Contrat'),
        ),
    ]
