# Generated by Django 2.1 on 2023-04-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0088_model_bon_reception_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employe',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
