# Generated by Django 2.1 on 2023-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0089_model_employe_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employe',
            name='cycle_diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_employe',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
