# Generated by Django 2.1 on 2023-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0090_auto_20230409_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_fonction',
            name='designation',
            field=models.CharField(max_length=250),
        ),
    ]
