from django.contrib import admin
from . import models

# Register your models here.
admin.site.register(models.Model_Personne)
admin.site.register(models.Model_Module)
admin.site.register(models.Model_SousModule)
admin.site.register(models.Model_ActionUtilisateur)
admin.site.register(models.Model_ActionSousModule)
admin.site.register(models.Model_Role)
admin.site.register(models.Model_RoleModule)
admin.site.register(models.Model_RoleSousModule)
admin.site.register(models.Model_RoleAction)
admin.site.register(models.Model_RoleUtilisateur)
admin.site.register(models.Model_Article)
admin.site.register(models.Model_TypeArticle)
admin.site.register(models.Model_Compte)
admin.site.register(models.Model_TypeCompte)
admin.site.register(models.Model_Devise)
admin.site.register(models.Model_Taux)
admin.site.register(models.Model_Document)
admin.site.register(models.Model_Droit)
admin.site.register(models.Model_Place)

admin.site.register(models.Model_Etat_Facturation)
admin.site.register(models.Model_Fonction)
admin.site.register(models.Model_Type_Diplome)
admin.site.register(models.Model_Diplome)




admin.site.register(models.Model_Bon_reception)
admin.site.register(models.Model_Bon)
admin.site.register(models.Model_Poste)
admin.site.register(models.Model_Ligne_reception)
admin.site.register(models.Model_Payloads)
admin.site.register(models.Model_Transaction)
admin.site.register(models.Model_Paiement)
admin.site.register(models.Model_Facture)
admin.site.register(models.Model_Ligne_facture)
admin.site.register(models.Model_Categorie)
admin.site.register(models.Model_Fournisseur)
admin.site.register(models.Model_Demande_achat)
admin.site.register(models.Model_Ligne_demande_achat)
admin.site.register(models.Model_Budget)
#admin.site.register(models.Model_Departement)
admin.site.register(models.Model_LigneBudgetaire)
admin.site.register(models.Model_ProfilRH)
admin.site.register(models.Model_Expression)
admin.site.register(models.Model_Ligne_Expression)

admin.site.register(models.Model_Dossier_Social)

admin.site.register(models.Model_Journal)
admin.site.register(models.Model_PieceComptable)
admin.site.register(models.Model_EcritureComptable)


admin.site.register(models.Model_Bon_inventaire)
admin.site.register(models.Model_Ligne_inventaire)
admin.site.register(models.Model_Bon_transfert)
admin.site.register(models.Model_Ligne_transfert)
admin.site.register(models.Model_Mouvement_stock)
admin.site.register(models.Model_Emplacement)
admin.site.register(models.Model_TypeEmplacement)
admin.site.register(models.Model_StockArticle)
admin.site.register(models.Model_OperationStock)
admin.site.register(models.Model_Unite)
admin.site.register(models.Model_Asset)


admin.site.register(models.Model_Unite_fonctionnelle)
admin.site.register(models.Model_TypeUnite_fonctionnelle)
#admin.site.register(models.Model_Grade)
admin.site.register(models.Model_Dependant)
admin.site.register(models.Model_ProfilPaye)
admin.site.register(models.Model_Ordre_paie)
admin.site.register(models.Model_Pret)
admin.site.register(models.Model_Conge)
admin.site.register(models.Model_Type_conge)
admin.site.register(models.Model_Employe)


admin.site.register(models.Model_Client)
admin.site.register(models.Model_Bon_commande)
admin.site.register(models.Model_Ligne_commande)
admin.site.register(models.Model_Condition_reglement)
admin.site.register(models.Model_ConditionReglement)
admin.site.register(models.Model_Bon_livraison)


admin.site.register(models.Model_Wkf_Workflow)
admin.site.register(models.Model_Wkf_Etape)
admin.site.register(models.Model_Wkf_Condition)
admin.site.register(models.Model_Wkf_Transition)
admin.site.register(models.Model_Wkf_Historique)
admin.site.register(models.Model_Wkf_Approbation)
admin.site.register(models.Model_Wkf_Stakeholder)

admin.site.register(models.Model_Notification)
admin.site.register(models.Model_Temp_Notification)
admin.site.register(models.Model_Message)

admin.site.register(models.Model_Exercicebudgetaire)
admin.site.register(models.Model_Projet)
admin.site.register(models.Model_Transactionbudgetaire)
admin.site.register(models.Model_Typetransactionbudgetaire)
admin.site.register(models.Model_Categoriebudget)
admin.site.register(models.Model_UniteAchatArticle)

admin.site.register(models.Model_Avis_appel_offre)

admin.site.register(models.Model_ModuleOverModel)

admin.site.register(models.Model_Categorie_employe)
admin.site.register(models.Model_Syndicat)
admin.site.register(models.Model_Ligne_Syndicat)
admin.site.register(models.Model_Evaluation)
admin.site.register(models.Model_Emploi)
admin.site.register(models.Model_Mobilite)
admin.site.register(models.Model_Formation)
admin.site.register(models.Model_Ligne_Formation)

admin.site.register(models.Model_Ligne_releve)
admin.site.register(models.Model_Projet_professionnel)
admin.site.register(models.Model_Recrutement_interne)

admin.site.register(models.Model_Centre_cout)

admin.site.register(models.Model_ItemBon)
admin.site.register(models.Model_AssetHistorique)
admin.site.register(models.Model_Taxe)
admin.site.register(models.Model_Annee_fiscale)
admin.site.register(models.Model_CaptureCompte)
admin.site.register(models.Model_Local)
admin.site.register(models.Model_Lettrage)
admin.site.register(models.Model_CompteBanque)
admin.site.register(models.Model_Caisse)
admin.site.register(models.Model_OperationTresorerie)
admin.site.register(models.Model_Ligne_OperationTresorerie)
admin.site.register(models.Model_Banque)
admin.site.register(models.Model_Requete)
admin.site.register(models.Model_Ligne_requete)
admin.site.register(models.Model_Ordre_de_mission)
admin.site.register(models.Model_Ligne_ordre_de_mission)

admin.site.register(models.Model_Activite)
admin.site.register(models.Model_Organisation)
admin.site.register(models.Model_Config_Comptabilite)

admin.site.register(models.Model_LigneBilleterie)
admin.site.register(models.Model_Billeterie)

admin.site.register(models.Model_Ecriture_analytique)
admin.site.register(models.Model_GroupeAnalytique)
admin.site.register(models.Model_ElementBulletin)

admin.site.register(models.Model_Immobilisation)

admin.site.register(models.Model_Ordre_paiement)
admin.site.register(models.Model_Ligne_ordre_paiement)
admin.site.register(models.Model_Analyse_indice_princsuivi)
admin.site.register(models.Model_Analyse_Personnel_Mouve)
admin.site.register(models.Model_Requete_competence)

admin.site.register(models.Model_CategorieRegle)
admin.site.register(models.Model_RegleSalariale)
admin.site.register(models.Model_TypeStructure)
admin.site.register(models.Model_StructureSalariale)

admin.site.register(models.Model_TypeEvenement)
admin.site.register(models.Model_Evenement)
admin.site.register(models.Model_Alarme)
admin.site.register(models.Model_Participant)

admin.site.register(models.Model_Recouvrement)
admin.site.register(models.Model_RecouvrementLigne)
admin.site.register(models.Model_RelanceRecouvrement)

admin.site.register(models.Model_Civilite)

admin.site.register(models.Model_GroupeMenu)
admin.site.register(models.Model_GroupePermission)
admin.site.register(models.Model_Permission)
admin.site.register(models.Model_Regle)
admin.site.register(models.Model_GroupePermissionUtilisateur)
admin.site.register(models.Model_LignePosteBudgetaire)
admin.site.register(models.Model_Poste_budgetaire)

admin.site.register(models.Model_Operationnalisation_module)
admin.site.register(models.Model_Typefacture)

admin.site.register(models.Model_Rubrique)
admin.site.register(models.Model_Constante)
admin.site.register(models.Model_ConstanteCalcul)
admin.site.register(models.Model_ConstanteTest)
admin.site.register(models.Model_ConstanteTranche)
admin.site.register(models.Model_BulletinModele)
admin.site.register(models.Model_DossierPaie)
admin.site.register(models.Model_Bulletin)
admin.site.register(models.Model_ItemBulletin)
admin.site.register(models.Model_LotBulletins)
admin.site.register(models.Model_ClassificationProfessionelle)
admin.site.register(models.Model_CompteBanque_Employe)
admin.site.register(models.Model_Rib)
admin.site.register(models.Model_LignesLot)
admin.site.register(models.Temp_EcritureComptable)

admin.site.register(models.Model_LignePaiementPret)
admin.site.register(models.Model_Config_Payroll)

admin.site.register(models.Model_MobiliteEmploye)
admin.site.register(models.Model_StatusRH)
admin.site.register(models.Model_TypeMarche)
admin.site.register(models.Model_Lettre_commande)
admin.site.register(models.Model_Demande_cotation)
admin.site.register(models.Model_Contrat)
admin.site.register(models.Model_OperationContrat)

admin.site.register(models.Model_Type_service)
admin.site.register(models.Model_Bon_retour)
admin.site.register(models.Model_TraitementImmobilisation)
admin.site.register(models.Model_LieuTravail)
admin.site.register(models.Model_Nature)
admin.site.register(models.Model_GroupementCombinaisonB)
admin.site.register(models.Model_Query)
