# Generated by Django 2.1 on 2022-03-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleStock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_emplacementstock',
            name='parent',
        ),
    ]
