# Generated by Django 2.1.14 on 2022-02-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ErpBackOffice', '0053_auto_20211213_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Action_relance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation')),
                ('date_action', models.DateField(verbose_name="Date de l'action")),
                ('montant_action', models.FloatField(blank=True, null=True, verbose_name="Montant de l'action")),
                ('observation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observation')),
                ('statut_action', models.IntegerField(choices=[(1, 'En cours'), (2, 'fermé')], verbose_name="Statut de l'action")),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_action_relance_jwv', to='ErpBackOffice.Model_Personne')),
            ],
            options={
                'verbose_name': 'Relance',
                'verbose_name_plural': 'Relances',
                'db_table': 'action_relance',
            },
        ),
        migrations.CreateModel(
            name='Model_Action_scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Désignation')),
                ('nb_jours', models.IntegerField(choices=[(-7, '-7 jours'), (-6, '-6 jours'), (-5, '-5 jours'), (-4, '-4 jours'), (-3, '-3 jours'), (-2, '-2 jours'), (-1, '-1 jour'), (0, '+0 jour'), (1, '+1 jours'), (2, '+2 jours'), (3, '+3 jours'), (4, '+4 jours'), (5, '+5 jours'), (6, '+6 jours'), (7, '+7 jours')], verbose_name='Nombre de jours')),
                ('type_action', models.CharField(choices=[('contentieux', 'Contentieux'), ('courrier1', 'Courrier (Lettre Simple)'), ('courrier2', 'Courrier LRAR (Lettre Récommandée avec Accusé de Réception'), ('courrier3', 'Courrier RE (Courrier Récommandé Electronique'), ('email', 'Email'), ('fax', 'Fax'), ('sms', 'SMS'), ('telephone', 'Téléphone')], max_length=250, verbose_name='Type action')),
                ('est_automatique', models.BooleanField(blank=True, default=False, null=True, verbose_name='Relance automatique')),
                ('description', models.CharField(blank=True, max_length=510, null=True, verbose_name='Description')),
                ('sujet', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sujet')),
                ('message', models.CharField(blank=True, max_length=510, null=True, verbose_name='Message')),
                ('langue', models.CharField(blank=True, max_length=250, null=True, verbose_name='Langue')),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_action_scenario_smi', to='ErpBackOffice.Model_Personne')),
            ],
            options={
                'verbose_name': 'Action du scénario de relance',
                'verbose_name_plural': 'Actions du scénario de relance',
                'db_table': 'action_scenario',
            },
        ),
        migrations.CreateModel(
            name='Model_Dossier_recouvrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Désignation')),
                ('description', models.CharField(blank=True, max_length=510, null=True, verbose_name='Description')),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_dossier_recouvrement_aiy', to='ErpBackOffice.Model_Personne')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_recouvrements_client', to='ErpBackOffice.Model_Client', verbose_name='Client')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape')),
            ],
            options={
                'verbose_name': 'Dossier de recouvrement',
                'verbose_name_plural': 'Dossiers de recouvrement',
                'db_table': 'dossier_recouvrement',
            },
        ),
        migrations.CreateModel(
            name='Model_Scenario_relance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Désignation')),
                ('description', models.CharField(blank=True, max_length=510, null=True, verbose_name='Description')),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_scenario_relance_bye', to='ErpBackOffice.Model_Personne')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape')),
            ],
            options={
                'verbose_name': 'Scénario de relance',
                'verbose_name_plural': 'Scénarios de relance',
                'db_table': 'scenario_relance',
            },
        ),
        migrations.AddField(
            model_name='model_action_scenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_scenarios_scenario', to='ModuleRecouvrement.Model_Scenario_relance', verbose_name='Scénarios de relance'),
        ),
        migrations.AddField(
            model_name='model_action_scenario',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape'),
        ),
        migrations.AddField(
            model_name='model_action_relance',
            name='dossier_recouvrement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_relances_dossier_recouvrement', to='ModuleRecouvrement.Model_Dossier_recouvrement', verbose_name='Dossier recouvremnet'),
        ),
        migrations.AddField(
            model_name='model_action_relance',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_relances_facture', to='ErpBackOffice.Model_Facture', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='model_action_relance',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape'),
        ),
    ]
