# Generated by Django 2.1.14 on 2022-02-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRecouvrement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_action_relance',
            name='type_action',
            field=models.CharField(choices=[('contentieux', 'Contentieux'), ('courrier1', 'Courrier (Lettre Simple)'), ('courrier2', 'Courrier LRAR (Lettre Récommandée avec Accusé de Réception'), ('courrier3', 'Courrier RE (Courrier Récommandé Electronique'), ('email', 'Email'), ('fax', 'Fax'), ('sms', 'SMS'), ('telephone', 'Téléphone')], default='email', max_length=250, verbose_name='Type action'),
        ),
    ]
