# Generated by Django 2.1.14 on 2022-02-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleRecouvrement', '0002_model_action_relance_type_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_action_scenario',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_scenarios_scenario', to='ModuleRecouvrement.Model_Scenario_relance', verbose_name='Scénarios de relance'),
        ),
    ]
