# Generated by Django 2.1.14 on 2022-03-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErpBackOffice', '0053_auto_20211213_1647'),
        ('ModuleRecouvrement', '0003_auto_20220210_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Profil_recouvrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Désignation')),
                ('description', models.CharField(blank=True, max_length=510, null=True, verbose_name='Description')),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_profil_recouvrement_aiy', to='ErpBackOffice.Model_Personne')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape')),
            ],
            options={
                'verbose_name': 'Profil recouvrement',
                'verbose_name_plural': 'Profils recouvrement',
                'db_table': 'profil_recouvrement',
            },
        ),
        migrations.CreateModel(
            name='Model_Secteur_activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Désignation')),
                ('description', models.CharField(blank=True, max_length=510, null=True, verbose_name='Description')),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auteur_de_model_secteur_activite_aiy', to='ErpBackOffice.Model_Personne')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ErpBackOffice.Model_Wkf_Etape')),
            ],
            options={
                'verbose_name': 'Secteur Activité',
                'verbose_name_plural': 'Secteurs Activité',
                'db_table': 'secteur_activite',
            },
        ),
    ]
